name: kings_league_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.5
  dartz: ^0.10.1
  equatable: ^2.0.5
  http: ^0.13.5
  get_it: ^7.2.0
  flutter_bloc: ^8.1.1
  rxdart: ^0.27.7
  palette_generator: ^0.3.3+2
  flutter_dotenv: ^5.0.2
  intl: ^0.17.0
  go_router: ^6.0.1
  flutter_svg: ^1.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.11.0
  flutter_lints: ^2.0.0

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/ic_launcher.jpg"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/env/
    - assets/icons/
    - assets/images/
